/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class be_beeles_place_jambiLight_utils_screenCapture_impl_ScreenCapperJNIMock */

#ifndef _Included_be_beeles_place_jambiLight_utils_screenCapture_impl_ScreenCapperJNIMock
#define _Included_be_beeles_place_jambiLight_utils_screenCapture_impl_ScreenCapperJNIMock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     be_beeles_place_jambiLight_utils_screenCapture_impl_ScreenCapperJNIMock
 * Method:    captureViaJNI
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_be_beeles_1place_jambiLight_utils_screenCapture_impl_ScreenCapperJNIMock_captureViaJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
